BEGIN_NAMESPACE_2(org, jace)

/**
 * Contains the template specialization prototypes for the template class, ElementProxy.
 *
 * This file is only for internal use of the JACE library.
 */

template <>
JACE_API JArray< ::org::jace::proxy::types::JBoolean >::JArray(int size);

template <>
JACE_API ElementProxy< ::org::jace::proxy::types::JBoolean > JArray< ::org::jace::proxy::types::JBoolean >::operator[](const int& index);

template <>
JACE_API const ElementProxy< ::org::jace::proxy::types::JBoolean > JArray< ::org::jace::proxy::types::JBoolean >::operator[](const int& index) const;

template <>
JACE_API JArray< ::org::jace::proxy::types::JByte >::JArray(int size);

template <>
JACE_API ElementProxy< ::org::jace::proxy::types::JByte > JArray< ::org::jace::proxy::types::JByte >::operator[](const int& index);

template <>
JACE_API const ElementProxy< ::org::jace::proxy::types::JByte > JArray< ::org::jace::proxy::types::JByte >::operator[](const int& index) const;

template <>
JACE_API JArray< ::org::jace::proxy::types::JChar >::JArray(int size);

template <>
JACE_API ElementProxy< ::org::jace::proxy::types::JChar > JArray< ::org::jace::proxy::types::JChar >::operator[](const int& index);

template <>
JACE_API const ElementProxy< ::org::jace::proxy::types::JChar > JArray< ::org::jace::proxy::types::JChar >::operator[](const int& index) const;

template <>
JACE_API JArray< ::org::jace::proxy::types::JDouble >::JArray(int size);

template <>
JACE_API ElementProxy< ::org::jace::proxy::types::JDouble > JArray< ::org::jace::proxy::types::JDouble >::operator[](const int& index);

template <>
JACE_API const ElementProxy< ::org::jace::proxy::types::JDouble > JArray< ::org::jace::proxy::types::JDouble >::operator[](const int& index) const;

template <>
JACE_API JArray< ::org::jace::proxy::types::JFloat >::JArray(int size);

template <>
JACE_API ElementProxy< ::org::jace::proxy::types::JFloat > JArray< ::org::jace::proxy::types::JFloat >::operator[](const int& index);

template <>
JACE_API const ElementProxy< ::org::jace::proxy::types::JFloat > JArray< ::org::jace::proxy::types::JFloat >::operator[](const int& index) const;

template <>
JACE_API JArray< ::org::jace::proxy::types::JInt >::JArray(int size);

template <>
JACE_API ElementProxy< ::org::jace::proxy::types::JInt > JArray< ::org::jace::proxy::types::JInt >::operator[](const int& index);

template <>
JACE_API const ElementProxy< ::org::jace::proxy::types::JInt > JArray< ::org::jace::proxy::types::JInt >::operator[](const int& index) const;

template <>
JACE_API JArray< ::org::jace::proxy::types::JLong >::JArray(int size);

template <>
JACE_API ElementProxy< ::org::jace::proxy::types::JLong > JArray< ::org::jace::proxy::types::JLong >::operator[](const int& index);

template <>
JACE_API const ElementProxy< ::org::jace::proxy::types::JLong > JArray< ::org::jace::proxy::types::JLong >::operator[](const int& index) const;

template <>
JACE_API JArray< ::org::jace::proxy::types::JShort >::JArray(int size);

template <>
JACE_API ElementProxy< ::org::jace::proxy::types::JShort > JArray< ::org::jace::proxy::types::JShort >::operator[](const int& index);

template <>
JACE_API const ElementProxy< ::org::jace::proxy::types::JShort > JArray< ::org::jace::proxy::types::JShort >::operator[](const int& index) const;

END_NAMESPACE_2(org, jace)

